name: "Verify Renovate JSON"

on: pull_request

jobs:
  verify-renovate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Verify renovate deafult.json
        env:
          RENOVATE_CONFIG_FILE: default.json
        run: |
          npx --yes --package renovate -- renovate-config-validator 
      - name: Verify renovate config
        env:
          RENOVATE_CONFIG_FILE: renovate.json
        run: |
          npx --yes --package renovate -- renovate-config-validator 
