name: "Verify Renovate JSON"

on: pull_request

jobs:
  verify-renovate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '24'
      - name: Verify renovate deafult.json
        env:
          RENOVATE_VERSION: 42.14.1
          RENOVATE_CONFIG_FILE: default.json
        run: |
          npx --yes --package renovate@${RENOVATE_VERSION} -- renovate-config-validator 